rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "home", to: "home#main"
  resources :lakes, only: [:index, :show], param: :slug
  resources :parks, only: [:index, :show], param: :slug
  resources :states, only: [:index, :show], param: :slug do
    get "parks", to: "parks#within_state"
    resources :parks, only: [:index, :show], param: :slug
  end
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/lake.rb
class Lake < ApplicationRecord
  def geojson
    RGeo::GeoJSON.encode(self.geo_boundary, json_parser: :json)
  end

  def area
    if self.geo_boundary
      ActiveRecord::Base.connection.execute("
      SELECT
        ST_Area(
          ST_Transform(ST_GeomFromText('#{self.geo_boundary.as_json}', #{self.geo_boundary.srid}), 4326)::geography
        ) / 1000000 AS area;
      ")[0]["area"].to_f
    end
  end

  def to_param
    slug
  end
end

rails/app/models/park.rb
class Park < ApplicationRecord
  belongs_to :state

  def geojson
    RGeo::GeoJSON.encode(self.geo_boundary || self.geo_boundary_multi, json_parser: :json)
  end

  def area
    geometry = (self.geo_boundary || self.geo_boundary_multi)
    if geometry
      ActiveRecord::Base.connection.execute("
      SELECT
        ST_Area(
          ST_Transform(ST_GeomFromText('#{geometry.as_json}', #{geometry.srid}), 4326)::geography
        ) / 1000000 AS area;
      ")[0]["area"].to_f
    end
  end

  def to_param
    slug
  end
end

rails/app/models/state.rb
class State < ApplicationRecord
  attribute :lat, :float
  attribute :lng, :float
  attribute :sw_lat, :float
  attribute :sw_lng, :float
  attribute :ne_lat, :float
  attribute :ne_lng, :float

  has_many :parks

  def geojson
    RGeo::GeoJSON.encode(self.geo_boundary || self.geo_boundary_multi, json_parser: :json).to_json
  end

  def area
    geometry = (self.geo_boundary || self.geo_boundary_multi)
    ActiveRecord::Base.connection.execute("
    SELECT
      ST_Area(
        ST_Transform(ST_GeomFromText('#{geometry.as_json}', #{geometry.srid}), 4326)::geography
      ) / 1000000 AS area;
    ")[0]["area"].to_f
  end

  def to_param
    slug
  end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  respond_to? :json

  def park_path(park)
    state_park_path(park.state, park)
  end

  helper_method :park_path
end

rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hide_nav = true
  end

  def main
  end
end

rails/app/controllers/lakes_controller.rb
class LakesController < ApplicationController
  def index
    @lakes = Lake.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @lakes }
    end
  end

  def show
    @hide_nav = true
    @lake = Lake.find_by! slug: params[:slug]
    respond_to do |format|
      format.html { render :lake }
      format.json { render json: @lake }
    end
  end
end

rails/app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    respond_to do |format|
      format.html {
        @states = State.includes(:parks).all
        render :index
      }
      format.json {
        @parks = Park.includes(:state).order(:state_id).all
        render json: @parks
      }
    end
  end

  def show
    @hide_nav = true
    @park = (params[:state_slug] ? (Park.includes(:state).where("states.slug" => params[:state_slug])) : Park).find_by! slug: params[:slug]
    respond_to do |format|
      format.html { render :park }
      format.json { render json: @park }
    end
  end

  def within_state
    @state = State.includes(:parks).find_by! slug: params[:state_slug]
    render :json => @state.parks.map { |park| park.attributes.except("geo_boundary", "geo_boundary_multi").merge(geojson: park.geojson) }
  end
end

rails/app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.includes(:parks).all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @states }
    end
  end

  def show
    @hide_nav = true
    @state = State.find_by! slug: params[:slug]
    respond_to do |format|
      format.html { render :state }
      format.json { render json: @state.attributes.except("geo_boundary", "geo_boundary_multi").merge(geojson: @state.geojson) }
    end
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/home_helper.rb
module HomeHelper
end

rails/app/helpers/lakes_helper.rb
module LakesHelper
end

rails/app/helpers/parks_helper.rb
module ParksHelper
end

rails/app/helpers/states_helper.rb
module StatesHelper
end

rails/app/views/home/index.html.erb
<div id="map"></div>
<script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      zoom: 5,
      center: new google.maps.LatLng(-27.19, 130.039),
      mapTypeId: "terrain"
    });

    var script = document.createElement("script");
    script.src = "./parks.js";
    document.getElementsByTagName("head")[0].appendChild(script);

    var script = document.createElement("script");
    script.src = "./states.js";
    document.getElementsByTagName("head")[0].appendChild(script);
  }

  window.states_callback = function(results) {
    map.data.addGeoJson(results);
    map.data.setStyle({
      fillColor: "green"
    });
  };
  window.parks_callback = function(results) {
    map.data.setStyle(function(feature) {
      return {
        fillColor: feature.getProperty("STATE_NAME") ? "green" : "red",
        strokeWeight: 1
      };
    });
    for (var i = 0; i < results.length; i++) {
      const coords = results[i].location.coordinates;
      const latLng = new google.maps.LatLng(coords[1], coords[0]);
      map.data.addGeoJson({
        type: "Feature",
        properties: {
          name: results[i].name
        },
        geometry: results[i].geojson
      });
      const marker = new google.maps.Marker({
        position: latLng,
        map: map,
        title: results[i].name
      });
    }
  };
</script>
<script
  async
  defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD91EoAwa0vdQxTIuhguQ8XRTLYtZ47TzM&callback=initMap"
></script>

rails/app/views/home/main.html.erb
<div class="d-flex flex-wrap align-items-center">
  <div>
    <h1>Australian Geography Data!</h1>
    <p>This project is for gathering geo spatial data on Australias National Parks, Lakes, States, etc.</p>
    <p>Also a project for me to learn Ruby on Rails.</p>
  </div>
  <img src="/images/australia.svg" alt="Australia" class="australia-img">
</div>

rails/app/views/lakes/index.html.erb
<h1>Lake List</h1>
<ul>
  <% @lakes.each do |lake| %>
    <li>
      <%= render lake %>
    </li>
  <% end %>
</ul>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Youcamp Geography Data</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if not @hide_nav %>
      <header class="site-header">
        <img src="/images/australia.svg" alt="Australia Geography Data">
        <nav class="main-nav">
          <%= link_to "Home", :home %>
          <%= link_to "States (#{State.count})", :states %>
          <%= link_to "Parks (#{Park.count})", :parks %>
          <%= link_to "Lakes (#{Lake.count})", :lakes %>
        </nav>
      </header>
      <div class="main-content">
    <% end %>
    <%= yield %>
    <% if not @hide_nav %>
      </div>
    <% end %>
  </body>
</html>

rails/app/views/parks/_park.html.erb
<p>
  <%= link_to park.name, park_path(park) %>
  <small><%= link_to park.state.abbrv_name, state_path(park.state) %></small>
</p>

rails/app/views/parks/index.html.erb
<h1>Park List</h1>
<% @states.each do |state| %>
  <h2>
    <%= state.full_name %>
    <small><%= pluralize state.parks.size, "park" %></small>
  </h2>
  <ul>
    <% state.parks.each do |park| %>
      <li>
        <%= render park %>
      </li>
    <% end %>
  </ul>
<% end %>

rails/app/views/parks/park.html.erb
<div class="map-info">
  <h1><%= @park.name %> (<%= @park.state.abbrv_name %>)</h1>
  <span class="loader">Loading parks...</span>
  <p>Page rendered at: <time><%= Time.now() %></time></p>
  <dl>
    <dt>Coords</dt>
    <dd><%= @park.lat %> lat, <%= @park.lng %> lng</dd>
    <dt>Overview</dt>
    <dd><%= @park.overview || "N/A" %></dd>
    <dt>Website</dt>
    <dd><%= @park.official_url || "N/A" %></dd>
    <dt>Timezone</dt>
    <dd><%= @park.timezone || "N/A" %></dd>
    <dt>Area</dt>
    <dd><%= number_to_human @park.area %> km&sup2;</dd>
  </dl>
</div>
<div id="map"></div>
<pre style="word-wrap:break-word;white-space:normal;"></pre>
<script>
  var map;
  var loader = document.querySelector(".map-info .loader");
  async function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      zoom: 5,
      center: new google.maps.LatLng(-27.19, 130.039),
      mapTypeId: "terrain"
    });

    map.data.setStyle({
      fillColor: "green",
      strokeWeight: 1
    });

    map.data.addGeoJson({
      type: "Feature",
      geometry: <%= @park.geojson.to_json.html_safe %>
    });

    const marker = new google.maps.Marker({
      position: { lat: <%= @park.lat %>, lng: <%= @park.lng %> },
      map: map,
      title: "<%= @park.name %>"
    });

    var bounds = new google.maps.LatLngBounds();
    map.data.forEach(function (feature) {
      feature.getGeometry().forEachLatLng(function (latlng) {
        bounds.extend(latlng);
      });
    });
    map.fitBounds(bounds, {top: 350, right: 350, bottom: 350, left: 350});
  }
</script>
<script
  async
  defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD91EoAwa0vdQxTIuhguQ8XRTLYtZ47TzM&callback=initMap"
></script>

rails/app/views/states/_state.html.erb
<p>
  <%= link_to state.full_name, state_path(state) %>
  <small><%= pluralize state.parks.size, "park" %></small>
</p>

rails/app/views/states/index.html.erb
<h1>State List</h1>
<ul>
  <% @states.each do |state| %>
    <li>
      <%= render state %>
    </li>
  <% end %>
</ul>

rails/app/views/states/state.html.erb
<div class="map-info">
  <h1><%= @state.full_name %> (<%= @state.abbrv_name %>)</h1>
  <span class="loader">Loading parks...</span>
  <p>Page rendered at: <time><%= Time.now() %></time></p>
  <dl>
    <dt>Coords</dt>
    <dd><%= @state.lat %> lat, <%= @state.lng %> lng</dd>
    <dt>Display Title</dt>
    <dd><%= @state.display_title || "N/A" %></dd>
    <dt>SEO Title</dt>
    <dd><%= @state.seo_title || "N/A" %></dd>
    <dt>SEO Description</dt>
    <dd><%= @state.seo_description || "N/A" %></dd>
    <dt>Parks</dt>
    <dd><%= @state.parks.size %></dd>
    <dt>Area</dt>
    <dd><%= number_to_human @state.area %> km&sup2;</dd>
  </dl>
</div>
<div id="map"></div>
<pre style="word-wrap:break-word;white-space:normal;"></pre>
<script>
  var map;
  var loader = document.querySelector(".map-info .loader");
  async function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      zoom: 5,
      center: new google.maps.LatLng(-27.19, 130.039),
      mapTypeId: "terrain"
    });

    map.data.setStyle({
      fillColor: "green",
      strokeWeight: 1
    });

    map.data.addGeoJson({
      type: "Feature",
      geometry: <%= @state.geojson.html_safe %>
    });

    const marker = new google.maps.Marker({
      position: { lat: <%= @state.lat %>, lng: <%= @state.lng %> },
      map: map,
      title: "<%= @state.full_name %>"
    });

    var sw_corner = { lat: <%= @state.sw_lat %>, lng: <%= @state.sw_lng %> };
    var ne_corner = { lat: <%= @state.ne_lat %>, lng: <%= @state.ne_lng %> };
    var bounds = new google.maps.LatLngBounds(sw_corner, ne_corner);
    map.fitBounds(bounds);

    loader.classList.add("show");
    var parks = await fetch("/states/<%= @state.slug %>/parks").then(res =>
      res.json()
    );
    loader.classList.remove("show");

    for (const park of parks) {
      map.data.addGeoJson({
        type: "Feature",
        geometry: park.geojson
      });
      const marker = new google.maps.Marker({
        position: { lat: park.lat, lng: park.lng },
        map: map,
        title: park.name
      });
    }

    console.log("Loaded " + parks.length + " parks");
  }
</script>
<script
  async
  defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD91EoAwa0vdQxTIuhguQ8XRTLYtZ47TzM&callback=initMap"
></script>